function s = getsysobjsupportedstructs
%GETSYSOBJSUPPORTEDSTRUCTS  Get structures supported by filter System objects

%   Copyright 2011 The MathWorks, Inc.
%   $Revision: 1.1.6.3 $  $Date: 2013/04/29 20:54:59 $

% This is a static method

s = {...
  'dffir', 'dffirt', 'dfsymfir','dfasymfir','latticemamin',...
  'df1sos','df1tsos','df2sos','df2tsos',...
  'df1','df1t','df2','df2t',...
  'firdecim','firtdecim','cicdecim',...
  'firinterp','linearinterp','cicinterp',...
  'firsrc', 'calattice', 'calatticepc',...
  'cascadeallpass', 'cascadewdfallpass'};
