function description = describe(~)
%DESCRIBE   

%   Copyright 2011 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2011/04/02 00:56:29 $

description = {...
'Filter Order';...
'First Stopband Frequency';...
'First Passband Frequency';...
'Second Passband Frequency';...
'Second Stopband Frequency'  
'Constraint for each Band'};

% [EOF]
