%TRIANG  三角ウィンドウ
%
%   W = TRIANG(N) は、N 点の三角ウィンドウを返します。
%
%   参考 BARTHANNWIN, BARTLETT, BLACKMANHARRIS, BOHMANWIN,
%        FLATTOPWIN, NUTTALLWIN, PARZENWIN, RECTWIN, WINDOW.


%   Copyright 1988-2007 The MathWorks, Inc.
